Two Controller layout
AusTINCANsProgrammingTeam/2022RobotCode pull request #103
Opened 2022-02-19 18:33 UTC by ModBoyex

2022-02-19 19:07 UTC, azvanderpas requested changes

2022-02-19 19:07 UTC, azvanderpas commented on src/main/java/frc/robot/RobotContainer.java
> +  private static final Joystick driverJoystick2 = new Joystick(Constants.portNumber1);
How about some more specific naming? Something like operatorJoystick

2022-02-19 19:07 UTC, azvanderpas commented on src/main/java/frc/robot/Constants.java
> +  public static final boolean testMode = true;
testMode is pretty vague. Maybe we could set it based on the number of controllers plugged in?

2022-02-19 19:19 UTC, sarango2158 commented on src/main/java/frc/robot/RobotContainer.java
> +  private static final Joystick driverJoystick2 = new Joystick(Constants.portNumber1);
+1

2022-02-19 19:37 UTC, sarango2158 requested changes
Still a lot more to do for the two different controller layouts we want to have:

- Climber should be on the left joystick on the operator controller for competition mode
- CDS override should be on operator's right bumper and right trigger for competition mode
- Intake should be on driver's right bumper and right trigger for competition mode
- Shoot should be on driver's left bumper and left trigger for competition mode
- Cycling shooter aim modes should only be available for test mode
- Should be able to switch controller layouts without rebuilding and re-deploying. Could be "smart" (detect number of joysticks) or could be a dashboard setting

2022-02-19 19:37 UTC, sarango2158 commented on src/main/java/frc/robot/RobotContainer.java
> +  private JoystickButton[] buttons2 = new JoystickButton[13];
Request better naming here too so it is easy to see which button collections are for which mapping.

2022-02-23 16:40 UTC, azvanderpas commented
Looks like the Climb base PR included these changes, so this one is now empty. Closing

2022-02-23 16:40 UTC, closed without merging