Drive Base
AusTINCANsProgrammingTeam/2022RobotCode pull request #117
Opened 2022-02-23 23:30 UTC by tonyn10

External encoders and auton modes/command groups

2022-02-24 00:02 UTC, azvanderpas commented on src/main/java/frc/robot/commands/AutonModes.java
> +                () -> driveBaseSubsystem.resetOdometry(taxiTrajectories[0].getInitialPose())));
taxiTrajectories should be oneBallTrajectories

2022-02-24 00:02 UTC, azvanderpas commented on src/main/java/frc/robot/commands/AutonModes.java
> +            "Autos/" + routeName); // get file with all the names of the path for the auton routine
Remember that only files/folders in the deploy directory will get copied to the roboRIO. You need to move Autos to the deploy directory.

2022-02-24 00:02 UTC, azvanderpas commented on src/main/java/frc/robot/commands/AutonModes.java
> +    Scanner fileScanner = null;
No need to assign to null
```suggestion
    Scanner fileScanner;
```

2022-02-24 00:04 UTC, sarango2158 requested changes

2022-02-24 00:04 UTC, sarango2158 commented on src/main/java/frc/robot/Constants.java
> +    ClimbSubsystem    (false);
reset to true before merging this PR into main

2022-02-24 00:04 UTC, sarango2158 commented on src/main/java/frc/robot/RobotContainer.java
> +    return chosenAutonMode;
I think this still needs to return null if drive base is disabled. Possibly have other subsystems that we should check now too

2022-02-24 00:17 UTC, azvanderpas commented on src/main/java/frc/robot/commands/AutonModes.java
> +            twoBallRamseteCommands[1], // goes to fender
Does the odometry need to be reset here as well?

2022-02-24 00:22 UTC, azvanderpas commented on src/main/java/frc/robot/commands/AutonModes.java
> +              driveBaseSubsystem);
```suggestion
              driveBaseSubsystem).beforeStarting(
                  () -> driveBaseSubsystem.resetOdometry(trajectories[i].getInitialPose()));
```

Then its bundled into all the ramsete commands and you don't have to redo it for each in initializeCommandGroups

2022-02-24 01:01 UTC, caseyjbrotherton approved these changes

2022-02-24 01:01 UTC, caseyjbrotherton commented on src/main/java/frc/robot/commands/AutonModes.java
> +        System.out.println("Trajectory: " + pathName + " not created.");
We should consider whether we want to have a driverstation error for this:

https://first.wpi.edu/wpilib/allwpilib/docs/release/java/edu/wpi/first/wpilibj/DriverStation.html#reportError(java.lang.String,boolean)

Not sure.  
Pro: Easier to see.  This error is important to know if one of our auton modes are broke.
Con:  More complicated, and we shouldn't see this error often, if at all.

2022-03-02 00:06 UTC, azvanderpas approved these changes

2022-03-02 00:06 UTC, azvanderpas commented on src/main/java/frc/robot/Constants.java
> +  public static final String taxioutball = "TaxiOutGrabBall.wpilib.json";
How about an array?

2022-03-02 00:06 UTC, azvanderpas commented on src/main/java/frc/robot/Constants.java
> +  public static final int driveRightRear = 4; // 7 on real robot
Revert before merging

2022-03-02 00:42 UTC, sarango2158 approved these changes

2022-03-02 00:58 UTC, merged