DriveBase
AusTINCANsProgrammingTeam/2022RobotCode pull request #5
Opened 2022-01-12 00:03 UTC by tonyn10

DriveBaseSubsystem class: arcade drive implemented, tank drive could be an extra thing implemented later.
DriveBaseTeleopCommand class
MotorController class: organizes all the SparkMax motor controllers.

2022-01-12 00:42 UTC, azvanderpas requested changes

2022-01-12 00:42 UTC, azvanderpas commented on src/main/java/frc/robot/Main.java
> -/**
Something wrong with block comments?

2022-01-12 00:42 UTC, azvanderpas commented on src/main/java/frc/robot/Constants.java
> +
Add a TODO comment to replace motor controller IDs with real values

2022-01-12 00:42 UTC, azvanderpas commented on src/main/java/frc/robot/RobotContainer.java
>    private final ExampleSubsystem m_exampleSubsystem = new ExampleSubsystem();
Don't forget to instantiation your command and subsystem here

2022-01-12 01:17 UTC, tonyn10 commented
> DriveBaseSubsystem class: arcade drive implemented, tank drive could be an extra thing implemented later. DriveBaseTeleopCommand class MotorController class: organizes all the SparkMax motor controllers.

Fixed comment format and Robot Container. Should be good to merge to main now.

2022-01-12 23:49 UTC, sarango2158 approved these changes
Excellent start, very clean and easy to read!

2022-01-13 00:52 UTC, azvanderpas approved these changes

2022-01-13 23:14 UTC, merged