Intake
AusTINCANsProgrammingTeam/2022RobotCode pull request #9
Opened 2022-01-14 00:47 UTC by Ariya3

2022-01-14 01:11 UTC, sarango2158 requested changes

2022-01-14 01:11 UTC, sarango2158 commented on src/main/java/frc/robot/Robot.java
> +    mAutonomousCommand = mRobotContainer.getAutonomousCommand();
Where did this come from? I don't see an AutonomousCommand class in main. Can we revert this back to a version before this was added?

2022-01-14 01:17 UTC, sarango2158 commented on src/main/java/frc/robot/Robot.java
> -import frc.robot.subsystems.IntakeSubsystem;
Not going to use the Intake and Hopper subsystems in Robot.java

2022-01-14 04:48 UTC, zainmfjavaid commented
Fixed autonomous command and robot.java comments. Should be good to merge now

2022-01-15 01:52 UTC, azvanderpas requested changes

2022-01-15 01:52 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/HopperSubsystem.java
> +  private MotorController[] mHopperController = new MotorController[1];
No reason to use an array here. Maybe if you expect to have more motors added eventually, but I don't think we do.

2022-01-15 01:52 UTC, azvanderpas commented on src/main/java/frc/robot/commands/HopperReverseCommand.java
> +    mHopperSubsystem.HopperSwitch(true);
Don't forget to add the direction controls.

2022-01-15 01:52 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    mIntakeMotorControllers[Constants.kIntakeMotorOneIndex] = new MotorController("Main Intake Motor", Constants.kIntakeMotorOneID);
Seems easier not to use an array for these.

2022-01-19 00:33 UTC, azvanderpas requested changes

2022-01-19 00:33 UTC, azvanderpas commented on src/main/java/frc/robot/commands/HopperForwardCommand.java
> +    mHopperSubsystem.ForwardHopper();
This could momentarily cause the motors to spin backwards and then change direction. Switch the order of these lines.

2022-01-19 00:33 UTC, azvanderpas commented on src/main/java/frc/robot/commands/HopperReverseCommand.java
> +    mHopperSubsystem.ReverseHopper();
Put this before the motor turn on.

2022-01-19 00:34 UTC, azvanderpas commented
Your branch needs to merge with the main branch before we can submit it.

2022-01-20 00:47 UTC, azvanderpas approved these changes

2022-01-20 01:00 UTC, sarango2158 approved these changes

2022-01-20 01:02 UTC, merged